# Generated by Django 5.0.3 on 2024-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Tagline', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=1000)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Views', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('Description1', models.TextField(max_length=1000)),
                ('Description2', models.TextField(max_length=1000)),
            ],
        ),
    ]
