# Generated by Django 5.0.1 on 2024-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainai',
            name='keywords',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mainai',
            name='version',
            field=models.CharField(choices=[('FR', 'Free'), ('PA', 'Paid'), ('FM', 'Freemium')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='mainai',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
