# Generated by Django 5.0.3 on 2024-03-16 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0003_alter_mainai_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainai',
            name='additional',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainai',
            name='category',
            field=models.CharField(default='default_category', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainai',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
